### ISSUE TITLE
Allow multiple pseudo-selectors of the same name

### ISSUE THREAD

**Issue by tomek-he-him** [tomekwi/jss-lite#1]
Right now it’s impossible to generate this stylesheet:

``` css
@font-face {
  font-family: MyHelvetica;
  src: url(MgOpenModernaBold.ttf);
  font-weight: bold;
}

@font-face {
  font-family: MyHelvetica;
  src: url(MgOpenModernaRegular.ttf);
  font-weight: normal;
}
```

The current idea is to handle it similarly to how we handle property fallbacks:

``` js
cssInJs([{
  '@font-face': {
    'font-family': 'MyHelvetica';
    src: 'url(MgOpenModernaBold.ttf)';
    'font-weight': 'bold';
  },
}, {
  '@font-face': {
    'font-family': 'MyHelvetica';
    src: 'url(MgOpenModernaRegular.ttf)';
    'font-weight': 'normal';
  },
}]);
```
